-- Catálogo cultural inicial investigado para el mapa de Nómada.
-- Horarios, tarifas y enlaces de respaldo se conservan en metadata para que
-- Administración pueda revisarlos sin modificar el modelo principal.
INSERT INTO "destinations" ("slug", "name", "department", "category", "description", "latitude", "longitude", "activities", "average_cost_min", "average_cost_max", "cost_currency", "content_status", "is_active", "metadata", "source_url") VALUES
('museo-ferrocarril-fegua', 'Museo del Ferrocarril FEGUA', 'Guatemala', 'Cultura', 'Antigua Estación Central con locomotoras, vagones y memoria ferroviaria de Guatemala.', 14.6294154, -90.5113736, '["Cultura","Historia","A pie","Museos"]', 0, 25, 'GTQ', 'published', true, '{"address":"9a. avenida A 18-03, zona 1, Ciudad de Guatemala","hours":"Martes a viernes 09:00-16:00; sábado y domingo 10:00-16:00","admission":"Consultar tarifa vigente antes de visitar","sourceName":"FEGUA / Centro Histórico","sourceUrl":"https://fegua.gob.gt/","lastVerified":"2026-09-01"}', 'https://fegua.gob.gt/'),
('museo-postal-correos', 'Museo Postal de Correos, Telégrafos y Filatelia', 'Guatemala', 'Cultura', 'Recorrido por la historia postal, telegráfica y filatélica de Guatemala en el Palacio de Correos.', 14.6349000, -90.5109000, '["Cultura","Historia","A pie","Museos"]', 0, 0, 'GTQ', 'published', true, '{"address":"7a. avenida 11-67, Palacio de Correos, segundo nivel, zona 1","hours":"Lunes a viernes 09:00-17:00; sábado 08:00-13:00","admission":"Entrada libre","sourceName":"Dirección General de Correos y Telégrafos","sourceUrl":"https://guatemala.gob.gt/el-museo-postal-acerca-a-la-juventud-a-la-historia/","lastVerified":"2026-09-01"}', 'https://guatemala.gob.gt/el-museo-postal-acerca-a-la-juventud-a-la-historia/'),
('museo-numismatico', 'Museo Numismático de Guatemala', 'Guatemala', 'Cultura', 'Colección del Banco de Guatemala sobre la evolución de la moneda, billetes y medios de pago del país.', 14.6260597, -90.5137643, '["Cultura","Historia","A pie","Museos"]', 0, 0, 'GTQ', 'published', true, '{"address":"7a. avenida 22-01, zona 1, Ciudad de Guatemala","hours":"Lunes a viernes 08:00-16:00","admission":"Entrada gratuita; grupos con reserva previa","sourceName":"Banco de Guatemala","sourceUrl":"https://www.banguat.gob.gt/page/museo-numismatico-de-guatemala-0","lastVerified":"2026-09-01"}', 'https://www.banguat.gob.gt/page/museo-numismatico-de-guatemala-0'),
('museo-nacional-historia', 'Museo Nacional de Historia', 'Guatemala', 'Historia', 'Doce salas y colecciones que recorren los procesos históricos que formaron Guatemala.', 14.6396458, -90.5099274, '["Cultura","Historia","A pie","Museos"]', 5, 50, 'GTQ', 'published', true, '{"address":"9a. calle 9-70, zona 1, Ciudad de Guatemala","hours":"Martes a viernes 09:00-17:00; sábado y domingo 10:00-16:00","admission":"Nacionales Q5; extranjeros Q50; menores de 12 años gratis","sourceName":"Ministerio de Cultura y Deportes","sourceUrl":"https://guatemala.gob.gt/museo-nacional-de-historia-un-recorrido-por-la-memoria-historica-de-guatemala/","lastVerified":"2026-09-01"}', 'https://guatemala.gob.gt/museo-nacional-de-historia-un-recorrido-por-la-memoria-historica-de-guatemala/'),
('centro-cultural-miguel-angel-asturias', 'Centro Cultural Miguel Ángel Asturias', 'Guatemala', 'Cultura', 'Complejo escénico nacional diseñado por Efraín Recinos, con la Gran Sala, Teatro de Cámara y espacios al aire libre.', 14.6274098, -90.5171572, '["Cultura","Teatro","A pie"]', 0, 250, 'GTQ', 'published', true, '{"address":"21 calle y 6a. avenida, Centro Cultural Miguel Ángel Asturias, Ciudad de Guatemala","hours":"Recorridos y eventos según programación; administración y visitas guiadas generalmente 09:00-17:00","admission":"La tarifa depende de la función o actividad","sourceName":"CulturaGuate / MCD","sourceUrl":"https://culturaguate.gob.gt/centro-cultural-miguel-angel-asturias/","lastVerified":"2026-09-01"}', 'https://culturaguate.gob.gt/centro-cultural-miguel-angel-asturias/'),
('teatro-abril', 'Teatro Abril', 'Guatemala', 'Cultura', 'Teatro histórico y monumento nacional dedicado a montajes, conciertos y actividades escénicas.', 14.6342021, -90.5122226, '["Cultura","Teatro","A pie"]', 0, 350, 'GTQ', 'published', true, '{"address":"9a. avenida 14-22, zona 1, Ciudad de Guatemala","hours":"Funciones y atención según cartelera; confirmar antes de visitar","admission":"La tarifa depende de la función","sourceName":"Teatro Abril","sourceUrl":"https://teatroabril.com/contactanos","lastVerified":"2026-09-01"}', 'https://teatroabril.com/contactanos'),
('museo-nacional-arte-maya', 'Museo Nacional de Arte Maya, Arqueología y Etnología', 'Guatemala', 'Cultura maya', 'Colecciones arqueológicas y etnológicas de Guatemala, con piezas que narran la herencia maya.', 14.5972500, -90.5295500, '["Cultura","Historia","A pie","Museos"]', 5, 100, 'GTQ', 'published', true, '{"address":"6a. calle y 7a. avenida, Salón 5, Finca La Aurora, zona 13","hours":"Martes a domingo 10:00-19:00","admission":"Nacionales Q25; internacionales Q100 según información de reapertura","sourceName":"Sistema de Información Cultural / MCD","sourceUrl":"https://www.sicultura.gob.gt/apertura-museo-nacional-de-arte-maya-arqueologia-y-etnologia/","lastVerified":"2026-09-01"}', 'https://www.sicultura.gob.gt/apertura-museo-nacional-de-arte-maya-arqueologia-y-etnologia/'),
('museo-arte-moderno-carlos-merida', 'Museo Nacional de Arte Moderno Carlos Mérida', 'Guatemala', 'Cultura', 'Museo de arte moderno guatemalteco con colección permanente, sala Carlos Mérida y exposiciones temporales.', 14.5975000, -90.5288890, '["Cultura","Arte","A pie","Museos"]', 5, 50, 'GTQ', 'published', true, '{"address":"Salón 6, Finca La Aurora, zona 13, Ciudad de Guatemala","hours":"Jueves a domingo 09:00-16:00","admission":"Nacionales Q5; extranjeros Q50; menores de 10 años gratis","sourceName":"Ministerio de Cultura y Deportes","sourceUrl":"https://mcd.gob.gt/museo-nacional-de-arte-moderno-carlos-merida/","lastVerified":"2026-09-01"}', 'https://mcd.gob.gt/museo-nacional-de-arte-moderno-carlos-merida/'),
('museo-historia-natural-jorge-ibarra', 'Museo Nacional de Historia Natural Jorge A. Ibarra', 'Guatemala', 'Naturaleza', 'Colecciones y actividades educativas dedicadas a la biodiversidad y la historia natural de Guatemala.', 14.5970663, -90.5298089, '["Naturaleza","Cultura","A pie","Museos"]', 5, 50, 'GTQ', 'published', true, '{"address":"7a. avenida, Finca La Aurora, zona 13, Ciudad de Guatemala","hours":"Martes a domingo 09:00-16:00","admission":"Nacionales Q5; extranjeros Q50","sourceName":"CulturaGuate / MCD","sourceUrl":"https://culturaguate.gob.gt/subpaginas/","lastVerified":"2026-09-01"}', 'https://culturaguate.gob.gt/subpaginas/'),
('museo-popol-vuh', 'Museo Popol Vuh', 'Guatemala', 'Cultura maya', 'Colección de arte prehispánico y colonial que propone un recorrido por la historia de Guatemala.', 14.6080267, -90.5051404, '["Cultura","Historia","A pie","Museos"]', 15, 45, 'GTQ', 'published', true, '{"address":"6a. calle final, Campus Universidad Francisco Marroquín, zona 10","hours":"Lunes a viernes 09:00-17:00; sábado 09:00-13:00; domingo cerrado","admission":"Adultos Q45; estudiantes Q25; niños Q15","sourceName":"Museo Popol Vuh / UFM","sourceUrl":"https://popolvuh.ufm.edu/","lastVerified":"2026-09-01"}', 'https://popolvuh.ufm.edu/'),
('museo-ixchel', 'Museo Ixchel del Traje Indígena', 'Guatemala', 'Cultura', 'Museo dedicado a la investigación, conservación y difusión de los textiles y la indumentaria indígena de Guatemala.', 14.6078457, -90.5058185, '["Cultura","Arte","A pie","Museos"]', 15, 50, 'GTQ', 'published', true, '{"address":"6a. calle final, Centro Cultural UFM, zona 10, Ciudad de Guatemala","hours":"Lunes a viernes 09:00-16:30; confirmar horarios especiales","admission":"Consultar tarifa vigente","sourceName":"Museo Ixchel","sourceUrl":"https://protejemuseoixchel.org/","lastVerified":"2026-09-01"}', 'https://protejemuseoixchel.org/')
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name", "department" = EXCLUDED."department", "category" = EXCLUDED."category", "description" = EXCLUDED."description", "latitude" = EXCLUDED."latitude", "longitude" = EXCLUDED."longitude", "activities" = EXCLUDED."activities", "average_cost_min" = EXCLUDED."average_cost_min", "average_cost_max" = EXCLUDED."average_cost_max", "cost_currency" = EXCLUDED."cost_currency", "content_status" = EXCLUDED."content_status", "is_active" = EXCLUDED."is_active", "metadata" = EXCLUDED."metadata", "source_url" = EXCLUDED."source_url", "updated_at" = now();

INSERT INTO "stamps" ("destination_id", "code", "name", "description", "color", "is_active")
SELECT d."id", 'NMD-CULT-' || upper(left(replace(d."slug", '-', '_'), 30)), 'Sello · ' || d."name", 'Sello de la colección cultural para ' || d."name", '#8655AA', true
FROM "destinations" d
WHERE d."slug" IN ('museo-ferrocarril-fegua','museo-postal-correos','museo-numismatico','museo-nacional-historia','centro-cultural-miguel-angel-asturias','teatro-abril','museo-nacional-arte-maya','museo-arte-moderno-carlos-merida','museo-historia-natural-jorge-ibarra','museo-popol-vuh','museo-ixchel')
ON CONFLICT ("destination_id") DO UPDATE SET "name" = EXCLUDED."name", "description" = EXCLUDED."description", "color" = EXCLUDED."color", "is_active" = true, "updated_at" = now();

INSERT INTO "routes" ("slug", "name", "description", "difficulty", "estimated_minutes", "distance_km", "is_active") VALUES
('ruta-museos-centro-historico', 'Ruta de Museos del Centro Histórico', 'Un recorrido a pie entre historia ferroviaria, comunicaciones, moneda e historia nacional.', 'easy', 240, 3.2, true),
('ruta-teatros-capital', 'Ruta de los Teatros', 'Teatro Abril y Centro Cultural Miguel Ángel Asturias: arquitectura, escena y memoria artística de la capital.', 'easy', 150, 2.4, true),
('ruta-museos-la-aurora', 'Ruta de Museos de La Aurora', 'Arte maya, arte moderno e historia natural en el circuito cultural de la zona 13.', 'easy', 210, 1.6, true),
('ruta-maya-y-textil', 'Ruta Maya y Textil', 'Dos colecciones complementarias para conocer arte prehispánico, historia y textiles indígenas.', 'easy', 150, 0.5, true)
ON CONFLICT ("slug") DO UPDATE SET "name" = EXCLUDED."name", "description" = EXCLUDED."description", "difficulty" = EXCLUDED."difficulty", "estimated_minutes" = EXCLUDED."estimated_minutes", "distance_km" = EXCLUDED."distance_km", "is_active" = true, "updated_at" = now();

DELETE FROM "route_stops" WHERE "route_id" IN (SELECT "id" FROM "routes" WHERE "slug" IN ('ruta-museos-centro-historico','ruta-teatros-capital','ruta-museos-la-aurora','ruta-maya-y-textil'));

INSERT INTO "route_stops" ("route_id", "destination_id", "position")
SELECT r."id", d."id", x."position"
FROM (VALUES
  ('ruta-museos-centro-historico', 'museo-ferrocarril-fegua', 1),
  ('ruta-museos-centro-historico', 'museo-postal-correos', 2),
  ('ruta-museos-centro-historico', 'museo-numismatico', 3),
  ('ruta-museos-centro-historico', 'museo-nacional-historia', 4),
  ('ruta-teatros-capital', 'teatro-abril', 1),
  ('ruta-teatros-capital', 'centro-cultural-miguel-angel-asturias', 2),
  ('ruta-museos-la-aurora', 'museo-nacional-arte-maya', 1),
  ('ruta-museos-la-aurora', 'museo-arte-moderno-carlos-merida', 2),
  ('ruta-museos-la-aurora', 'museo-historia-natural-jorge-ibarra', 3),
  ('ruta-maya-y-textil', 'museo-popol-vuh', 1),
  ('ruta-maya-y-textil', 'museo-ixchel', 2)
) AS x("route_slug", "destination_slug", "position")
INNER JOIN "routes" r ON r."slug" = x."route_slug"
INNER JOIN "destinations" d ON d."slug" = x."destination_slug";
