-- México · segunda colección editorial. Tarifas y horarios se dejan vacíos
-- deliberadamente: varían por temporada y deben revisarse en Administración.
INSERT INTO destinations (slug,name,country,country_code,department,category,description,latitude,longitude,activities,cost_currency,points,content_status,is_active,source_url,metadata)
VALUES
('palenque-mx','Zona Arqueológica de Palenque','México','MX','Chiapas','Sitio arqueológico','Ciudad maya entre selva tropical, templos y museo de sitio.',17.4849,-92.0464,'["Cultura","Historia","A pie"]','MXN',170,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Palenque","sourceName":"INAH"}'),
('bonampak-mx','Zona Arqueológica de Bonampak','México','MX','Chiapas','Sitio arqueológico','Sitio maya célebre por sus murales conservados.',16.7047,-91.0652,'["Cultura","Historia","Naturaleza"]','MXN',150,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Ocosingo","sourceName":"INAH"}'),
('yaxchilan-mx','Zona Arqueológica de Yaxchilán','México','MX','Chiapas','Sitio arqueológico','Antigua ciudad maya accesible por el río Usumacinta.',16.8992,-90.9656,'["Cultura","Historia","Agua"]','MXN',160,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Ocosingo","sourceName":"INAH"}'),
('calakmul-mx','Reserva de la Biosfera y Ciudad Maya de Calakmul','México','MX','Campeche','Naturaleza','Bosque tropical protegido con una gran ciudad maya.',18.1043,-89.8108,'["Cultura","Naturaleza","Fauna"]','MXN',190,'published',true,'https://www.gob.mx/conanp/prensa/areas-naturales-protegidas-sitios-para-conocer-y-disfrutar-24281','{"city":"Calakmul","sourceName":"CONANP / INAH"}'),
('uxmal-mx','Zona Arqueológica de Uxmal','México','MX','Yucatán','Sitio arqueológico','Arquitectura Puuc y la Pirámide del Adivino.',20.3596,-89.7715,'["Cultura","Historia","A pie"]','MXN',160,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Santa Elena","sourceName":"INAH"}'),
('ek-balam-mx','Zona Arqueológica de Ek Balam','México','MX','Yucatán','Sitio arqueológico','Acrópolis maya y entorno de selva y cenotes.',20.8927,-88.1361,'["Cultura","Historia","A pie"]','MXN',150,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Temozón","sourceName":"INAH"}'),
('coba-mx','Zona Arqueológica de Cobá','México','MX','Quintana Roo','Sitio arqueológico','Red de sacbés mayas entre lagunas y selva.',20.4903,-87.7323,'["Cultura","Historia","Bicicleta"]','MXN',150,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Tulum","sourceName":"INAH"}'),
('bacalar-mx','Laguna de Bacalar','México','MX','Quintana Roo','Agua','Laguna de tonos turquesa y actividades de bajo impacto.',18.6813,-88.3937,'["Agua","Naturaleza","Fotografía"]','MXN',140,'published',true,'https://www.gob.mx/conanp/acciones-y-programas/areas-naturales-protegidas-51333','{"city":"Bacalar","sourceName":"Nómada editorial"}'),
('sian-kaan-mx','Reserva de la Biosfera Sian Ka’an','México','MX','Quintana Roo','Naturaleza','Reserva costera de humedales, arrecifes y selva.',19.3747,-87.7010,'["Naturaleza","Fauna","Agua"]','MXN',180,'published',true,'https://www.gob.mx/conanp/prensa/areas-naturales-protegidas-sitios-para-conocer-y-disfrutar-24281','{"city":"Tulum","sourceName":"CONANP"}'),
('isla-holbox-mx','Isla Holbox','México','MX','Quintana Roo','Playa','Isla caribeña de playas, aves y atardeceres.',21.5221,-87.3773,'["Playa","Fauna","Atardeceres"]','MXN',130,'published',true,'https://visitmexico.com/','{"city":"Lázaro Cárdenas","sourceName":"Visit Mexico"}'),
('cozumel-mx','Parque Nacional Arrecifes de Cozumel','México','MX','Quintana Roo','Playa','Arrecifes caribeños para buceo y snorkel responsable.',20.4229,-87.0229,'["Agua","Buceo","Naturaleza"]','MXN',170,'published',true,'https://www.gob.mx/conanp/prensa/areas-naturales-protegidas-sitios-para-conocer-y-disfrutar-24281','{"city":"Cozumel","sourceName":"CONANP"}'),
('balandra-mx','Playa Balandra','México','MX','Baja California Sur','Playa','Bahía de aguas tranquilas y paisaje desértico-marino.',24.3191,-110.3184,'["Playa","Agua","Fotografía"]','MXN',130,'published',true,'https://visitmexico.com/','{"city":"La Paz","sourceName":"Visit Mexico"}'),
('cabo-pulmo-mx','Parque Nacional Cabo Pulmo','México','MX','Baja California Sur','Naturaleza','Arrecife coralino protegido en el mar de Cortés.',23.4401,-109.4305,'["Agua","Buceo","Fauna"]','MXN',180,'published',true,'https://www.gob.mx/conanp/prensa/areas-naturales-protegidas-sitios-para-conocer-y-disfrutar-24281','{"city":"Los Cabos","sourceName":"CONANP"}'),
('espiritu-santo-mx','Archipiélago Espíritu Santo','México','MX','Baja California Sur','Naturaleza','Islas, lobos marinos y paisajes del golfo de California.',24.5434,-110.4078,'["Agua","Fauna","Buceo"]','MXN',180,'published',true,'https://www.gob.mx/conanp/prensa/areas-naturales-protegidas-sitios-para-conocer-y-disfrutar-24281','{"city":"La Paz","sourceName":"CONANP"}'),
('barrancas-cobre-mx','Barrancas del Cobre','México','MX','Chihuahua','Naturaleza','Sistema de cañones de la Sierra Tarahumara.',27.5274,-107.7807,'["Naturaleza","Aventura","Miradores"]','MXN',170,'published',true,'https://visitmexico.com/','{"city":"Urique","sourceName":"Visit Mexico"}'),
('monte-alban-mx','Zona Arqueológica de Monte Albán','México','MX','Oaxaca','Sitio arqueológico','Antigua capital zapoteca sobre una montaña nivelada.',17.0435,-96.7679,'["Cultura","Historia","A pie"]','MXN',170,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Oaxaca de Juárez","sourceName":"INAH"}'),
('oaxaca-centro-mx','Centro Histórico de Oaxaca','México','MX','Oaxaca','Cultura','Patrimonio urbano, mercados, arte y gastronomía oaxaqueña.',17.0608,-96.7253,'["Cultura","Gastronomía","A pie"]','MXN',120,'published',true,'https://patrimoniomundialmexico.inah.gob.mx/publico/listado_pm.php','{"city":"Oaxaca de Juárez","sourceName":"INAH"}'),
('canon-sumidero-mx','Parque Nacional Cañón del Sumidero','México','MX','Chiapas','Naturaleza','Cañón fluvial con recorridos en lancha y miradores.',16.8240,-93.0921,'["Naturaleza","Agua","Fauna"]','MXN',150,'published',true,'https://www.gob.mx/conanp/prensa/las-areas-naturales-protegidas-abren-sus-puertas-al-turismo-sustentable','{"city":"Chiapa de Corzo","sourceName":"CONANP"}'),
('lagunas-montebello-mx','Parque Nacional Lagunas de Montebello','México','MX','Chiapas','Naturaleza','Lagos de colores entre bosque y frontera sur.',16.1096,-91.7296,'["Naturaleza","Agua","Senderismo"]','MXN',150,'published',true,'https://www.gob.mx/conanp/prensa/las-areas-naturales-protegidas-abren-sus-puertas-al-turismo-sustentable','{"city":"La Trinitaria","sourceName":"CONANP"}'),
('agua-azul-mx','Cascadas de Agua Azul','México','MX','Chiapas','Agua','Cascadas y pozas de color turquesa en la selva.',17.2747,-92.1157,'["Agua","Naturaleza","Fotografía"]','MXN',140,'published',true,'https://www.gob.mx/conanp/prensa/conanp-refuerza-operativo-semana-santa-segura-para-atencion-de-turistas-en-areas-naturales-protegidas','{"city":"Tumbalá","sourceName":"CONANP"}'),
('huatulco-mx','Parque Nacional Huatulco','México','MX','Oaxaca','Playa','Bahías, arrecifes y bosque tropical seco.',15.7469,-96.1204,'["Playa","Agua","Naturaleza"]','MXN',150,'published',true,'https://www.gob.mx/conanp/prensa/las-areas-naturales-protegidas-abren-sus-puertas-al-turismo-sustentable','{"city":"Santa María Huatulco","sourceName":"CONANP"}'),
('puerto-escondido-mx','Puerto Escondido','México','MX','Oaxaca','Playa','Costa del Pacífico conocida por surf, playas y atardeceres.',15.8710,-97.0775,'["Playa","Surf","Atardeceres"]','MXN',120,'published',true,'https://visitmexico.com/','{"city":"San Pedro Mixtepec","sourceName":"Visit Mexico"}'),
('islas-marietas-mx','Parque Nacional Islas Marietas','México','MX','Nayarit','Naturaleza','Islas protegidas de biodiversidad marina en Bahía de Banderas.',20.6981,-105.5658,'["Agua","Fauna","Buceo"]','MXN',180,'published',true,'https://www.gob.mx/conanp/prensa/las-areas-naturales-protegidas-abren-sus-puertas-al-turismo-sustentable','{"city":"Bahía de Banderas","sourceName":"CONANP"}'),
('sayulita-mx','Sayulita','México','MX','Nayarit','Playa','Pueblo costero de surf y cultura local.',20.8689,-105.4416,'["Playa","Surf","Gastronomía"]','MXN',110,'published',true,'https://visitmexico.com/','{"city":"Bahía de Banderas","sourceName":"Visit Mexico"}'),
('cdmx-centro-historico-mx','Centro Histórico de Ciudad de México','México','MX','Ciudad de México','Historia','Zócalo, arquitectura virreinal y museos del centro.',19.4326,-99.1332,'["Historia","Cultura","A pie"]','MXN',130,'published',true,'https://patrimoniomundialmexico.inah.gob.mx/publico/listado_pm.php','{"city":"Ciudad de México","sourceName":"INAH"}'),
('templo-mayor-mx','Museo y Zona Arqueológica del Templo Mayor','México','MX','Ciudad de México','Sitio arqueológico','Recinto ceremonial mexica junto al Zócalo.',19.4348,-99.1319,'["Cultura","Historia","Museos"]','MXN',150,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Ciudad de México","sourceName":"INAH"}'),
('xochimilco-mx','Canales de Xochimilco','México','MX','Ciudad de México','Cultura','Canales, trajineras y paisaje cultural lacustre.',19.2574,-99.1046,'["Cultura","Agua","Gastronomía"]','MXN',130,'published',true,'https://whc.unesco.org/','{"city":"Ciudad de México","sourceName":"UNESCO"}'),
('chapultepec-mx','Bosque de Chapultepec','México','MX','Ciudad de México','Cultura','Bosque urbano con castillo, museos y lagos.',19.4204,-99.1811,'["Cultura","Naturaleza","Museos"]','MXN',110,'published',true,'https://visitmexico.com/','{"city":"Ciudad de México","sourceName":"Visit Mexico"}'),
('nevado-toluca-mx','Nevado de Toluca','México','MX','Estado de México','Volcanes','Volcán y lagunas de alta montaña.',19.1087,-99.7589,'["Volcanes","Senderismo","Naturaleza"]','MXN',170,'published',true,'https://www.gob.mx/conanp/acciones-y-programas/areas-naturales-protegidas-51333','{"city":"Toluca","sourceName":"CONANP"}'),
('mariposa-monarca-mx','Reserva de la Biosfera Mariposa Monarca','México','MX','Michoacán','Naturaleza','Bosques de oyamel visitados por mariposas monarca en temporada.',19.5965,-100.2712,'["Naturaleza","Fauna","Senderismo"]','MXN',170,'published',true,'https://www.gob.mx/conanp/prensa/areas-naturales-protegidas-sitios-para-conocer-y-disfrutar-24281','{"city":"Ocampo","sourceName":"CONANP"}'),
('izta-popo-mx','Parque Nacional Iztaccíhuatl-Popocatépetl','México','MX','Estado de México','Volcanes','Alta montaña, bosques y vistas volcánicas.',19.1785,-98.6428,'["Volcanes","Senderismo","Aventura"]','MXN',190,'published',true,'https://www.gob.mx/conanp/prensa/areas-naturales-protegidas-sitios-para-conocer-y-disfrutar-24281','{"city":"Amecameca","sourceName":"CONANP"}'),
('pico-orizaba-mx','Parque Nacional Pico de Orizaba','México','MX','Veracruz','Volcanes','Montaña más alta de México y parque de alta montaña.',19.0305,-97.2695,'["Volcanes","Aventura","Senderismo"]','MXN',200,'published',true,'https://www.gob.mx/conanp/acciones-y-programas/areas-naturales-protegidas-51333','{"city":"Tlachichuca","sourceName":"CONANP"}'),
('el-tajin-mx','Zona Arqueológica El Tajín','México','MX','Veracruz','Sitio arqueológico','Ciudad totonaca de la Pirámide de los Nichos.',20.4461,-97.3795,'["Cultura","Historia","A pie"]','MXN',160,'published',true,'https://www.inah.gob.mx/zonas','{"city":"Papantla","sourceName":"INAH"}'),
('san-miguel-allende-mx','San Miguel de Allende','México','MX','Guanajuato','Historia','Ciudad histórica de arte, arquitectura y vida cultural.',20.9144,-100.7436,'["Historia","Cultura","Gastronomía"]','MXN',120,'published',true,'https://whc.unesco.org/','{"city":"San Miguel de Allende","sourceName":"UNESCO"}'),
('guanajuato-ciudad-mx','Ciudad de Guanajuato','México','MX','Guanajuato','Historia','Calles, túneles, teatros y patrimonio minero.',21.0190,-101.2574,'["Historia","Cultura","A pie"]','MXN',120,'published',true,'https://whc.unesco.org/','{"city":"Guanajuato","sourceName":"UNESCO"}'),
('xilitla-mx','Jardín Surrealista de Xilitla','México','MX','San Luis Potosí','Cultura','Esculturas surrealistas en selva de la Huasteca.',21.3867,-98.9988,'["Arte","Naturaleza","Fotografía"]','MXN',130,'published',true,'https://visitmexico.com/','{"city":"Xilitla","sourceName":"Visit Mexico"}'),
('huasteca-potosina-mx','Cascadas de la Huasteca Potosina','México','MX','San Luis Potosí','Agua','Ríos, cascadas y pozas de la región Huasteca.',21.9147,-99.0934,'["Agua","Naturaleza","Aventura"]','MXN',160,'published',true,'https://visitmexico.com/','{"city":"Ciudad Valles","sourceName":"Visit Mexico"}'),
('grutas-tolantongo-mx','Grutas de Tolantongo','México','MX','Hidalgo','Agua','Grutas, río termal y pozas escalonadas en cañón.',20.6501,-99.0064,'["Agua","Naturaleza","Bienestar"]','MXN',150,'published',true,'https://visitmexico.com/','{"city":"Cardonal","sourceName":"Visit Mexico"}'),
('valle-guadalupe-mx','Valle de Guadalupe','México','MX','Baja California','Gastronomía','Valle vitivinícola y paisajes del norte de Baja California.',32.0384,-116.6347,'["Gastronomía","Naturaleza","Fotografía"]','MXN',130,'published',true,'https://visitmexico.com/','{"city":"Ensenada","sourceName":"Visit Mexico"}')
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, department=EXCLUDED.department, category=EXCLUDED.category, description=EXCLUDED.description, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, activities=EXCLUDED.activities, source_url=EXCLUDED.source_url, metadata=EXCLUDED.metadata, updated_at=now();

INSERT INTO stamps (destination_id,code,name,description,color,is_active)
SELECT id, 'NMD-MX-' || upper(left(replace(slug,'-','_'),30)), 'Sello · ' || name, 'Sello de exploración en México para ' || name, '#C95B3D', true
FROM destinations WHERE country_code='MX'
ON CONFLICT (destination_id) DO NOTHING;
