-- Honduras, El Salvador y Nicaragua · colección regional inicial.
-- Las fichas se pueden enriquecer desde Administración; las fuentes quedan
-- guardadas para mantener trazabilidad editorial.
INSERT INTO destinations (slug,name,country,country_code,department,category,description,latitude,longitude,activities,cost_currency,points,content_status,is_active,source_url,metadata) VALUES
('rio-platano-hn','Reserva de la Biosfera Río Plátano','Honduras','HN','Gracias a Dios','Naturaleza','Bosques tropicales, ríos y biodiversidad de la Mosquitia hondureña.',15.7480,-84.6520,'["Naturaleza","Fauna","Aventura"]','HNL',220,'published',true,'https://whc.unesco.org/en/list/196','{"city":"La Mosquitia","sourceName":"UNESCO"}'),
('cayos-cochinos-hn','Monumento Natural Marino Cayos Cochinos','Honduras','HN','Islas de la Bahía','Playa','Arrecifes, comunidades isleñas y vida marina del Caribe.',15.9820,-86.4790,'["Playa","Agua","Buceo","Fauna"]','HNL',190,'published',true,'https://www.visithonduras.com/','{"city":"Cayos Cochinos","sourceName":"Instituto Hondureño de Turismo"}'),
('utila-hn','Isla de Útila','Honduras','HN','Islas de la Bahía','Playa','Isla caribeña conocida por buceo, arrecifes y ambiente relajado.',16.0990,-86.8990,'["Playa","Buceo","Agua"]','HNL',160,'published',true,'https://www.visithonduras.com/','{"city":"Útila","sourceName":"Instituto Hondureño de Turismo"}'),
('lago-yojoa-hn','Lago de Yojoa','Honduras','HN','Cortés','Naturaleza','El lago natural más grande de Honduras, rodeado de bosques y miradores.',14.8730,-87.9850,'["Naturaleza","Agua","Fauna"]','HNL',140,'published',true,'https://www.visithonduras.com/','{"city":"Santa Cruz de Yojoa","sourceName":"Instituto Hondureño de Turismo"}'),
('pulhapanzak-hn','Cataratas de Pulhapanzak','Honduras','HN','Cortés','Agua','Cascada de gran caudal junto al Lago de Yojoa.',14.8920,-87.9790,'["Agua","Naturaleza","Aventura"]','HNL',150,'published',true,'https://www.visithonduras.com/','{"city":"San Buenaventura","sourceName":"Instituto Hondureño de Turismo"}'),
('celaque-hn','Parque Nacional Celaque','Honduras','HN','Lempira','Naturaleza','Bosque nuboso y senderos hacia el Cerro Las Minas.',14.5570,-88.6520,'["Naturaleza","Senderismo","Aventura"]','HNL',200,'published',true,'https://www.visithonduras.com/','{"city":"Gracias","sourceName":"Instituto Hondureño de Turismo"}'),
('comayagua-hn','Centro Histórico de Comayagua','Honduras','HN','Comayagua','Historia','Plazas, iglesias coloniales y el reloj histórico de Comayagua.',14.4510,-87.6370,'["Historia","Cultura","A pie"]','HNL',120,'published',true,'https://www.visithonduras.com/','{"city":"Comayagua","sourceName":"Instituto Hondureño de Turismo"}'),
('fortaleza-omoa-hn','Fortaleza de San Fernando de Omoa','Honduras','HN','Cortés','Historia','Fortaleza colonial frente al Caribe hondureño.',15.7720,-88.0340,'["Historia","Cultura","A pie"]','HNL',130,'published',true,'https://www.visithonduras.com/','{"city":"Omoa","sourceName":"Instituto Hondureño de Turismo"}'),
('la-tigra-hn','Parque Nacional La Tigra','Honduras','HN','Francisco Morazán','Naturaleza','Bosque nuboso, senderos y miradores cercanos a Tegucigalpa.',14.2040,-87.1800,'["Naturaleza","Senderismo","Fauna"]','HNL',160,'published',true,'https://www.visithonduras.com/','{"city":"Tegucigalpa","sourceName":"Instituto Hondureño de Turismo"}'),
('lancetilla-hn','Jardín Botánico Lancetilla','Honduras','HN','Atlántida','Naturaleza','Jardín botánico tropical y reserva de aves en la costa norte.',15.7420,-87.4690,'["Naturaleza","Fauna","Fotografía"]','HNL',140,'published',true,'https://www.visithonduras.com/','{"city":"Tela","sourceName":"Instituto Hondureño de Turismo"}'),
('joya-ceren-sv','Sitio Arqueológico Joya de Cerén','El Salvador','SV','La Libertad','Sitio arqueológico','Aldea agrícola maya preservada por ceniza volcánica.',13.8120,-89.3690,'["Cultura","Historia","A pie"]','USD',180,'published',true,'https://whc.unesco.org/en/list/675','{"city":"San Juan Opico","sourceName":"UNESCO"}'),
('suchitoto-sv','Suchitoto','El Salvador','SV','Cuscatlán','Cultura','Ciudad de calles empedradas, arte y vistas del lago Suchitlán.',13.9380,-89.7240,'["Cultura","Historia","Gastronomía"]','USD',130,'published',true,'https://www.visitcentroamerica.com/','{"city":"Suchitoto","sourceName":"Visit Centroamérica"}'),
('cerro-verde-sv','Parque Nacional Cerro Verde','El Salvador','SV','Santa Ana','Volcanes','Bosque de montaña y vistas hacia los volcanes de occidente.',13.8440,-89.6300,'["Volcanes","Naturaleza","Senderismo"]','USD',170,'published',true,'https://www.visitcentroamerica.com/','{"city":"Santa Ana","sourceName":"Visit Centroamérica"}'),
('lago-coatepeque-sv','Lago de Coatepeque','El Salvador','SV','Santa Ana','Agua','Lago de cráter de aguas azules con miradores y actividades acuáticas.',13.8640,-89.5410,'["Agua","Naturaleza","Fotografía"]','USD',150,'published',true,'https://www.visitcentroamerica.com/','{"city":"El Congo","sourceName":"Visit Centroamérica"}'),
('el-imposible-sv','Parque Nacional El Imposible','El Salvador','SV','Ahuachapán','Naturaleza','Bosque tropical protegido con rutas de senderismo y fauna.',13.7800,-89.9540,'["Naturaleza","Senderismo","Fauna"]','USD',190,'published',true,'https://www.visitcentroamerica.com/','{"city":"San Francisco Menéndez","sourceName":"Visit Centroamérica"}'),
('tazumal-sv','Parque Arqueológico Tazumal','El Salvador','SV','Santa Ana','Sitio arqueológico','Complejo ceremonial prehispánico en Chalchuapa.',13.9810,-89.6740,'["Cultura","Historia","A pie"]','USD',140,'published',true,'https://www.visitcentroamerica.com/','{"city":"Chalchuapa","sourceName":"Visit Centroamérica"}'),
('el-zonte-sv','Playa El Zonte','El Salvador','SV','La Libertad','Playa','Costa del Pacífico con surf, playas rocosas y atardeceres.',13.4940,-89.4350,'["Playa","Surf","Atardeceres"]','USD',120,'published',true,'https://www.visitcentroamerica.com/','{"city":"Tamanique","sourceName":"Visit Centroamérica"}'),
('costa-del-sol-sv','Costa del Sol','El Salvador','SV','La Paz','Playa','Litoral de playa, esteros y deportes acuáticos.',13.2790,-88.8950,'["Playa","Agua","Atardeceres"]','USD',120,'published',true,'https://www.visitcentroamerica.com/','{"city":"San Luis La Herradura","sourceName":"Visit Centroamérica"}'),
('apaneca-sv','Apaneca','El Salvador','SV','Ahuachapán','Aventura','Pueblo de montaña, cafetales y experiencias de la Ruta de las Flores.',13.8070,-89.8030,'["Aventura","Café","Naturaleza"]','USD',130,'published',true,'https://www.visitcentroamerica.com/','{"city":"Apaneca","sourceName":"Visit Centroamérica"}'),
('volcan-masaya-ni','Parque Nacional Volcán Masaya','Nicaragua','NI','Masaya','Volcanes','Cráter activo y paisaje volcánico accesible desde Managua y Granada.',11.9840,-86.1610,'["Volcanes","Naturaleza","Fotografía"]','NIO',180,'published',true,'https://www.visitcentroamerica.com/','{"city":"Nindirí","sourceName":"Visit Centroamérica"}'),
('laguna-apoyo-ni','Reserva Natural Laguna de Apoyo','Nicaragua','NI','Masaya','Agua','Laguna de cráter para nadar, remar y descansar entre bosque seco.',11.9320,-86.0530,'["Agua","Naturaleza","Bienestar"]','NIO',150,'published',true,'https://www.visitcentroamerica.com/','{"city":"Catarina","sourceName":"Visit Centroamérica"}'),
('leon-historica-ni','Centro Histórico de León','Nicaragua','NI','León','Historia','Ciudad universitaria de arquitectura colonial, arte y tradición cultural.',12.4360,-86.8780,'["Historia","Cultura","A pie"]','NIO',130,'published',true,'https://www.visitcentroamerica.com/','{"city":"León","sourceName":"Visit Centroamérica"}'),
('leon-viejo-ni','Ruinas de León Viejo','Nicaragua','NI','León','Historia','Restos arqueológicos de la primera ciudad colonial española en Nicaragua.',12.3990,-86.6120,'["Historia","Cultura","A pie"]','NIO',180,'published',true,'https://whc.unesco.org/en/list/613','{"city":"La Paz Centro","sourceName":"UNESCO"}'),
('cerro-negro-ni','Volcán Cerro Negro','Nicaragua','NI','León','Volcanes','Volcán joven de arena negra, popular para senderismo y sandboarding.',12.5060,-86.7020,'["Volcanes","Aventura","Senderismo"]','NIO',190,'published',true,'https://www.visitcentroamerica.com/','{"city":"León","sourceName":"Visit Centroamérica"}'),
('isletas-granada-ni','Las Isletas de Granada','Nicaragua','NI','Granada','Agua','Archipiélago de pequeñas islas volcánicas en el lago de Nicaragua.',11.9910,-86.0030,'["Agua","Naturaleza","Fauna"]','NIO',160,'published',true,'https://www.visitcentroamerica.com/','{"city":"Granada","sourceName":"Visit Centroamérica"}'),
('mombacho-ni','Reserva Natural Volcán Mombacho','Nicaragua','NI','Granada','Volcanes','Bosque nuboso y miradores sobre Granada y el lago de Nicaragua.',11.8310,-86.0330,'["Volcanes","Naturaleza","Senderismo"]','NIO',190,'published',true,'https://www.visitcentroamerica.com/','{"city":"Granada","sourceName":"Visit Centroamérica"}'),
('corn-island-ni','Corn Island','Nicaragua','NI','Costa Caribe Sur','Playa','Isla caribeña de playas, arrecifes y cultura afrocaribeña.',12.1690,-83.0410,'["Playa","Agua","Buceo"]','NIO',170,'published',true,'https://www.visitcentroamerica.com/','{"city":"Corn Island","sourceName":"Visit Centroamérica"}'),
('little-corn-island-ni','Little Corn Island','Nicaragua','NI','Costa Caribe Sur','Playa','Pequeña isla sin vehículos, con playas y arrecifes caribeños.',12.2870,-83.0370,'["Playa","Agua","Buceo"]','NIO',180,'published',true,'https://www.visitcentroamerica.com/','{"city":"Little Corn Island","sourceName":"Visit Centroamérica"}'),
('canon-somoto-ni','Cañón de Somoto','Nicaragua','NI','Madriz','Naturaleza','Cañón fluvial de roca para recorridos de aventura y agua dulce.',13.4840,-86.5820,'["Naturaleza","Agua","Aventura"]','NIO',180,'published',true,'https://www.visitcentroamerica.com/','{"city":"Somoto","sourceName":"Visit Centroamérica"}'),
('miraflor-ni','Reserva Natural Miraflor','Nicaragua','NI','Estelí','Naturaleza','Paisajes rurales, bosque de niebla y observación de aves.',13.1450,-86.2880,'["Naturaleza","Senderismo","Fauna"]','NIO',170,'published',true,'https://www.visitcentroamerica.com/','{"city":"Estelí","sourceName":"Visit Centroamérica"}')
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, country=EXCLUDED.country, country_code=EXCLUDED.country_code, department=EXCLUDED.department, category=EXCLUDED.category, description=EXCLUDED.description, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, activities=EXCLUDED.activities, cost_currency=EXCLUDED.cost_currency, points=EXCLUDED.points, source_url=EXCLUDED.source_url, metadata=EXCLUDED.metadata, updated_at=now();

INSERT INTO stamps (destination_id,code,name,description,color,is_active)
SELECT id, 'NMD-' || country_code || '-' || upper(left(replace(slug,'-','_'),28)), 'Sello · ' || name, 'Sello de exploración Nómada para ' || name, CASE country_code WHEN 'HN' THEN '#1F769A' WHEN 'SV' THEN '#405DAD' ELSE '#4A997C' END, true
FROM destinations WHERE country_code IN ('HN','SV','NI')
ON CONFLICT (destination_id) DO NOTHING;
