import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from 'react';
import { Award, BarChart3, Bell, Check, ChevronRight, FileCheck2, Flag, LayoutDashboard, LoaderCircle, LogOut, Map, MapPin, Menu, Plus, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react';

const API_URL = (import.meta.env.VITE_NOMADA_API_URL || 'https://api-nomada.innovasoftgt.com/api/v1').replace(/\/$/, '');
const MAPS_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY || '';
type Session = { accessToken: string; refreshToken: string; user: { id: string; email: string; role: string; profile?: { fullName?: string } } };
type Point = { latitude: number; longitude: number; visitCount?: number; label?: string; visitedAt?: string };
type Page = 'overview' | 'users' | 'destinations' | 'moderation' | 'verifications' | 'rewards';

declare global { interface Window { google?: any; nomadaGoogleMapsPromise?: Promise<void> } }

function readSession(): Session | undefined { try { const stored = sessionStorage.getItem('nomada-admin-session'); return stored ? JSON.parse(stored) : undefined; } catch { return undefined; } }
function saveSession(session?: Session) { if (session) sessionStorage.setItem('nomada-admin-session', JSON.stringify(session)); else sessionStorage.removeItem('nomada-admin-session'); }
function formatNumber(value?: number) { return new Intl.NumberFormat('es-GT').format(value ?? 0); }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat('es-GT', { dateStyle: 'medium' }).format(new Date(value)) : '—'; }
function slugify(value: string) { return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }

function loadGoogleMaps() {
  if (!MAPS_KEY || window.google?.maps) return Promise.resolve();
  if (!window.nomadaGoogleMapsPromise) window.nomadaGoogleMapsPromise = new Promise((resolve, reject) => {
    const script = document.createElement('script'); script.async = true; script.defer = true;
    script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(MAPS_KEY)}&v=weekly`;
    script.onload = () => resolve(); script.onerror = () => reject(new Error('No se pudo cargar Google Maps.'));
    document.head.appendChild(script);
  });
  return window.nomadaGoogleMapsPromise;
}

function GoogleMapPanel({ points, onPick, className = '' }: { points: Point[]; onPick?: (point: { latitude: number; longitude: number }) => void; className?: string }) {
  const ref = useRef<HTMLDivElement>(null); const [message, setMessage] = useState('');
  useEffect(() => {
    let disposed = false;
    if (!MAPS_KEY) { setMessage('Agrega VITE_GOOGLE_MAPS_API_KEY para visualizar el mapa de Google.'); return; }
    void loadGoogleMaps().then(() => {
      if (disposed || !ref.current || !window.google?.maps) return;
      const maps = window.google.maps; const center = points[0] ? { lat: points[0].latitude, lng: points[0].longitude } : { lat: 15.7835, lng: -90.2308 };
      const map = new maps.Map(ref.current, { center, zoom: points.length ? 8 : 7, disableDefaultUI: true, zoomControl: true, clickableIcons: false, styles: [{ featureType: 'poi.business', stylers: [{ visibility: 'off' }] }, { featureType: 'poi.medical', stylers: [{ visibility: 'off' }] }] });
      const bounds = new maps.LatLngBounds();
      points.forEach((point) => { const position = { lat: Number(point.latitude), lng: Number(point.longitude) }; bounds.extend(position); new maps.Circle({ map, center: position, radius: Math.max(65, Math.min(380, (point.visitCount ?? 1) * 48)), fillColor: '#E4A93C', fillOpacity: .42, strokeColor: '#0E5B4D', strokeOpacity: .85, strokeWeight: 1.5 }); });
      if (points.length > 1) map.fitBounds(bounds, 45);
      if (onPick) map.addListener('click', (event: any) => onPick({ latitude: Number(event.latLng.lat().toFixed(6)), longitude: Number(event.latLng.lng().toFixed(6)) }));
    }).catch((error: Error) => setMessage(error.message));
    return () => { disposed = true; };
  }, [points, onPick]);
  return <div className={`google-map ${className}`}><div ref={ref} className="google-map-canvas" />{message && <div className="map-empty"><MapPin size={20} /><span>{message}</span></div>}</div>;
}

function useApi(initial?: Session) {
  const [session, setSession] = useState<Session | undefined>(initial);
  const logout = () => { saveSession(); setSession(undefined); };
  const request = async <T,>(path: string, init: RequestInit = {}, retry = true): Promise<T> => {
    const live = session ?? readSession(); const headers = new Headers(init.headers); headers.set('Content-Type', 'application/json'); if (live?.accessToken) headers.set('Authorization', `Bearer ${live.accessToken}`);
    const response = await fetch(`${API_URL}${path}`, { ...init, headers });
    if (response.status === 401 && retry && live?.refreshToken) {
      const refresh = await fetch(`${API_URL}/auth/refresh`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refreshToken: live.refreshToken }) });
      if (refresh.ok) { const tokens = await refresh.json(); const next = { ...live, accessToken: tokens.accessToken, refreshToken: tokens.refreshToken }; saveSession(next); setSession(next); return request<T>(path, init, false); }
      logout();
    }
    if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.message || body.error || `Error HTTP ${response.status}`); }
    return response.status === 204 ? (undefined as T) : response.json();
  };
  return { session, setSession, request, logout };
}

function Login({ onReady }: { onReady: (session: Session) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try {
    const response = await fetch(`${API_URL}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, deviceName: 'Portal Nómada Administración' }) }); const data = await response.json();
    if (!response.ok) throw new Error(data.message || 'No fue posible iniciar sesión.');
    if (data.user?.role !== 'admin') throw new Error('Tu cuenta no tiene el rol de administrador. Un administrador existente debe habilitarla.');
    const next = { accessToken: data.accessToken, refreshToken: data.refreshToken, user: data.user }; saveSession(next); onReady(next);
  } catch (reason) { setError(reason instanceof Error ? reason.message : 'Ocurrió un error inesperado.'); } finally { setBusy(false); } };
  return <main className="login-shell"><section className="login-art"><div className="brand-mark"><Sparkles size={23} /> NÓMADA</div><div><p className="eyebrow light">CENTRO DE CONTROL</p><h1>Tu territorio,<br />bien cuidado.</h1><p>Gestiona lugares, comunidad y decisiones con información clara y verificable.</p></div><div className="login-art-orb one" /><div className="login-art-orb two" /></section><section className="login-card-wrap"><form className="login-card" onSubmit={submit}><div className="brand-mobile"><Sparkles size={20} /> NÓMADA</div><p className="eyebrow">ACCESO RESTRINGIDO</p><h2>Bienvenido de vuelta</h2><p className="muted">Inicia sesión con una cuenta que tenga rol de administrador.</p><label>Correo administrativo<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" required placeholder="nombre@innovasoftgt.com" /></label><label>Contraseña<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" required placeholder="••••••••" /></label>{error && <p className="form-error">{error}</p>}<button className="button primary full" disabled={busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <ShieldCheck size={18} />} {busy ? 'Validando acceso…' : 'Entrar al centro de control'}</button><p className="login-note"><ShieldCheck size={14} /> Actividad administrativa auditada.</p></form></section></main>;
}

const nav: Array<{ id: Page; label: string; icon: typeof LayoutDashboard }> = [
  { id: 'overview', label: 'Resumen', icon: LayoutDashboard }, { id: 'users', label: 'Viajeros', icon: Users }, { id: 'destinations', label: 'Lugares', icon: MapPin }, { id: 'moderation', label: 'Comunidad', icon: Flag }, { id: 'verifications', label: 'Certificaciones', icon: FileCheck2 }, { id: 'rewards', label: 'Sellos y logros', icon: Award },
];

function AdminShell({ api }: { api: ReturnType<typeof useApi> }) {
  const [page, setPage] = useState<Page>('overview'); const [mobileOpen, setMobileOpen] = useState(false);
  const content = page === 'overview' ? <Overview request={api.request} /> : page === 'users' ? <UsersPage request={api.request} /> : page === 'destinations' ? <DestinationsPage request={api.request} /> : page === 'moderation' ? <ModerationPage request={api.request} /> : page === 'verifications' ? <VerificationsPage request={api.request} /> : <RewardsPage request={api.request} />;
  return <div className="admin-shell"><aside className={mobileOpen ? 'sidebar open' : 'sidebar'}><div className="sidebar-brand"><div className="sidebar-logo"><Sparkles size={19} /></div><span>NÓMADA <small>CONTROL</small></span><button className="icon-button mobile-only" onClick={() => setMobileOpen(false)}><X size={20} /></button></div><nav>{nav.map((item) => { const Icon = item.icon; return <button key={item.id} className={page === item.id ? 'nav-item active' : 'nav-item'} onClick={() => { setPage(item.id); setMobileOpen(false); }}><Icon size={18} />{item.label}</button>; })}</nav><div className="sidebar-bottom"><div className="admin-ident"><div className="avatar">{(api.session?.user.profile?.fullName || api.session?.user.email || 'A').slice(0, 1).toUpperCase()}</div><div><strong>{api.session?.user.profile?.fullName || 'Administrador'}</strong><span>Administración</span></div></div><button className="nav-item logout" onClick={api.logout}><LogOut size={18} />Salir</button></div></aside><main className="admin-main"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><div><p className="eyebrow">NÓMADA · ADMINISTRACIÓN</p><h1>{nav.find((item) => item.id === page)?.label}</h1></div><div className="topbar-actions"><button className="icon-button"><Bell size={19} /><span className="notification-dot" /></button><div className="status-chip"><span /> Sistema operativo</div></div></header>{content}</main></div>;
}

function Overview({ request }: { request: ReturnType<typeof useApi>['request'] }) {
  const [data, setData] = useState<any>(); const [points, setPoints] = useState<Point[]>([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([request<any>('/admin/overview'), request<any>('/admin/analytics/visit-map')]).then(([overview, map]) => { setData(overview); setPoints(map.data); }).catch((reason) => setError(reason.message)); }, [request]);
  if (error) return <ErrorState message={error} />; if (!data) return <LoadingState label="Leyendo el pulso de Nómada…" />;
  const metrics = [{ label: 'Viajeros registrados', value: data.metrics.totalUsers, icon: Users, tone: 'green' }, { label: 'Visitas verificadas', value: data.metrics.totalVisits, icon: MapPin, tone: 'gold' }, { label: 'Lugares publicados', value: data.metrics.publishedDestinations, icon: Map, tone: 'blue' }, { label: 'Certificaciones pendientes', value: data.metrics.pendingVerifications, icon: FileCheck2, tone: 'coral' }];
  return <div className="page-content"><section className="welcome-row"><div><h2>Buen día. Todo bajo control.</h2><p>Vista de los últimos 30 días · actividad turística, comunidad y contenido.</p></div><div className="range-badge"><BarChart3 size={17} /> Actualizado en tiempo real</div></section><section className="metric-grid">{metrics.map(({ label, value, icon: Icon, tone }) => <article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={19} /></div><p>{label}</p><strong>{formatNumber(value)}</strong><span>{label === 'Visitas verificadas' ? `${formatNumber(data.metrics.visitsInRange)} en 30 días` : 'Dato consolidado'}</span></article>)}</section><section className="dashboard-grid"><article className="panel activity-panel"><PanelHeader title="Movimiento de la comunidad" subtitle="Nuevos viajeros y visitas verificadas" /><ActivityChart rows={data.activity} /><div className="chart-legend"><span><i className="legend-dot green" /> Viajeros nuevos</span><span><i className="legend-dot gold" /> Visitas</span></div></article><article className="panel top-panel"><PanelHeader title="Destinos con más movimiento" subtitle="Visitas verificadas en 30 días" /><ol className="ranking-list">{data.topDestinations.map((destination: any, index: number) => <li key={destination.id}><b>{String(index + 1).padStart(2, '0')}</b><div><strong>{destination.name}</strong><span>{destination.department}</span></div><em>{formatNumber(destination.visitCount)} visitas</em></li>)}</ol></article></section><section className="panel map-panel"><PanelHeader title="Mapa de actividad turística" subtitle="Concentración agregada de visitas verificadas. No es rastreo en vivo." /><GoogleMapPanel points={points} /><div className="map-footnote"><ShieldCheck size={15} /> Los puntos se agrupan por zona para proteger la privacidad. Consulta detalle individual solo desde el perfil autorizado del viajero.</div></section></div>;
}

function ActivityChart({ rows }: { rows: Array<{ day: string; users: number; visits: number }> }) {
  const values = rows.length ? rows : [{ day: new Date().toISOString(), users: 0, visits: 0 }]; const max = Math.max(1, ...values.flatMap((row) => [Number(row.users), Number(row.visits)]));
  const width = 620; const height = 190; const toPoints = (key: 'users' | 'visits') => values.map((row, index) => `${(index / Math.max(1, values.length - 1)) * width},${height - (Number(row[key]) / max) * 150 - 14}`).join(' ');
  return <div className="activity-chart"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none"><line x1="0" y1="176" x2={width} y2="176" className="chart-base" /><polyline points={toPoints('visits')} className="chart-line gold" /><polyline points={toPoints('users')} className="chart-line green" /></svg><div className="chart-dates"><span>{formatDate(values[0]?.day)}</span><span>{formatDate(values[values.length - 1]?.day)}</span></div></div>;
}

function UsersPage({ request }: { request: ReturnType<typeof useApi>['request'] }) {
  const [data, setData] = useState<any[]>([]); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<any>(); const [error, setError] = useState('');
  const load = () => request<any>(`/admin/users${query ? `?q=${encodeURIComponent(query)}` : ''}`).then((result) => setData(result.data)).catch((reason) => setError(reason.message)); useEffect(() => { void load(); }, []);
  const update = async (user: any, patch: any) => { await request(`/admin/users/${user.id}`, { method: 'PATCH', body: JSON.stringify(patch) }); await load(); setSelected((current: any) => current && { ...current, ...patch }); };
  return <div className="page-content"><section className="page-title-row"><div><h2>Viajeros y acceso</h2><p>Administra cuentas sin exponer documentos ni localización innecesaria.</p></div><div className="secure-note"><ShieldCheck size={16} /> Cambios auditados</div></section><div className="toolbar"><label className="search-box"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Nombre, correo o usuario" /></label><button className="button secondary" onClick={() => void load()}>Buscar</button></div>{error && <ErrorState message={error} />}<section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Viajero</th><th>Estado</th><th>Visitas</th><th>Registro</th><th /></tr></thead><tbody>{data.map((user) => <tr key={user.id}><td><div className="table-person"><div className="avatar">{user.fullName?.slice(0, 1)}</div><div><strong>{user.fullName}</strong><span>@{user.username} · {user.email}</span></div></div></td><td><span className={`state-pill ${user.status}`}>{user.status === 'active' ? 'Activo' : 'Suspendido'}</span><small>{user.role === 'admin' ? 'Administrador' : 'Viajero'}</small></td><td>{formatNumber(user.visitCount)}</td><td>{formatDate(user.createdAt)}</td><td><button className="table-action" onClick={() => setSelected(user)}>Ver <ChevronRight size={16} /></button></td></tr>)}</tbody></table>{!data.length && <Empty label="No encontramos viajeros con ese criterio." />}</div></section>{selected && <UserDrawer user={selected} onClose={() => setSelected(undefined)} request={request} onUpdate={update} />}</div>;
}

function UserDrawer({ user, request, onClose, onUpdate }: { user: any; request: ReturnType<typeof useApi>['request']; onClose: () => void; onUpdate: (user: any, patch: any) => Promise<void> }) {
  const [visits, setVisits] = useState<any[]>([]); const [error, setError] = useState(''); useEffect(() => { request<any>(`/admin/users/${user.id}/visits`).then((result) => setVisits(result.data)).catch((reason) => setError(reason.message)); }, [user.id]);
  const points = visits.map((visit) => ({ latitude: visit.latitude, longitude: visit.longitude, label: visit.destinationName, visitedAt: visit.visitedAt }));
  return <div className="drawer-backdrop"><aside className="drawer"><button className="drawer-close" onClick={onClose}><X size={21} /></button><p className="eyebrow">PERFIL DE VIAJERO</p><h2>{user.fullName}</h2><p className="muted">{user.email} · @{user.username}</p><div className="detail-stats"><div><strong>{formatNumber(user.visitCount)}</strong><span>visitas</span></div><div><strong>{user.verificationStatus || 'unverified'}</strong><span>certificación</span></div></div><div className="drawer-actions"><button className="button secondary" onClick={() => void onUpdate(user, { status: user.status === 'active' ? 'suspended' : 'active' })}>{user.status === 'active' ? 'Suspender cuenta' : 'Reactivar cuenta'}</button>{user.role !== 'admin' && <button className="button secondary" onClick={() => void onUpdate(user, { role: 'admin' })}>Hacer administrador</button>}</div><section><PanelHeader title="Historial de visitas" subtitle="Acceso excepcional auditado · últimos 12 meses" />{error ? <p className="form-error">{error}</p> : <GoogleMapPanel points={points} className="small-map" />}<div className="visit-list">{visits.slice(0, 8).map((visit) => <div key={visit.id}><MapPin size={15} /><span><strong>{visit.destinationName}</strong><small>{visit.department} · {formatDate(visit.visitedAt)}</small></span></div>)}</div></section></aside></div>;
}

function DestinationsPage({ request }: { request: ReturnType<typeof useApi>['request'] }) {
  const [data, setData] = useState<any[]>([]); const [formOpen, setFormOpen] = useState(false); const [error, setError] = useState('');
  const load = () => request<any>('/admin/destinations').then((result) => setData(result.data)).catch((reason) => setError(reason.message)); useEffect(() => { void load(); }, []);
  return <div className="page-content"><section className="page-title-row"><div><h2>Lugares y puntos Nómada</h2><p>Crea destinos turísticos o puntos comerciales con coordenadas precisas.</p></div><button className="button primary" onClick={() => setFormOpen(true)}><Plus size={17} /> Nuevo lugar</button></section>{error && <ErrorState message={error} />}<section className="destination-grid">{data.map((row) => <article className="destination-card" key={row.destination.id}><div className="destination-card-cover"><MapPin size={27} /><span className={row.destination.contentStatus === 'published' ? 'published-dot' : 'draft-dot'}>{row.destination.contentStatus === 'published' ? 'Publicado' : 'Borrador'}</span></div><div><p className="eyebrow">{row.destination.category}</p><h3>{row.destination.name}</h3><p>{row.destination.department} · {Number(row.destination.latitude).toFixed(5)}, {Number(row.destination.longitude).toFixed(5)}</p><div className="destination-card-footer"><span><Award size={14} /> {row.stamp?.name || 'Sin sello'}</span><button onClick={() => { navigator.clipboard?.writeText(`${row.destination.latitude}, ${row.destination.longitude}`); }}>Copiar coordenadas</button></div></div></article>)}</section>{!data.length && <Empty label="Todavía no hay lugares creados." />}{formOpen && <DestinationForm request={request} onClose={() => setFormOpen(false)} onCreated={() => { setFormOpen(false); void load(); }} />}</div>;
}

function DestinationForm({ request, onClose, onCreated }: { request: ReturnType<typeof useApi>['request']; onClose: () => void; onCreated: () => void }) {
  const [name, setName] = useState(''); const [department, setDepartment] = useState('Guatemala'); const [category, setCategory] = useState('Cultura'); const [description, setDescription] = useState(''); const [latitude, setLatitude] = useState('14.6349'); const [longitude, setLongitude] = useState('-90.5069'); const [stampName, setStampName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await request('/admin/destinations', { method: 'POST', body: JSON.stringify({ slug: slugify(name), name, department, category, description, latitude: Number(latitude), longitude: Number(longitude), validationRadiusMeters: 100, activities: [category], contentStatus: 'draft', isActive: true, points: 100, stamp: { code: `STAMP-${slugify(name).toUpperCase().slice(0, 28)}`, name: stampName || `Sello ${name}`, isActive: true } }) }); onCreated(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo crear el lugar.'); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><form className="modal destination-form" onSubmit={submit}><header><div><p className="eyebrow">NUEVO PUNTO</p><h2>Agregar lugar Nómada</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={20} /></button></header><p className="muted">Haz clic sobre el mapa o escribe las coordenadas si es un comercio o punto especial.</p><GoogleMapPanel points={[{ latitude: Number(latitude), longitude: Number(longitude) }]} onPick={(point) => { setLatitude(String(point.latitude)); setLongitude(String(point.longitude)); }} className="picker-map" /><div className="form-grid"><label>Nombre<input value={name} onChange={(event) => setName(event.target.value)} required placeholder="Café Museo Nómada" /></label><label>Departamento<input value={department} onChange={(event) => setDepartment(event.target.value)} required /></label><label>Categoría<input value={category} onChange={(event) => setCategory(event.target.value)} required placeholder="Cultura, gastronomía…" /></label><label>Nombre del sello<input value={stampName} onChange={(event) => setStampName(event.target.value)} placeholder="Sello Café Nómada" /></label><label>Latitud<input type="number" step="any" value={latitude} onChange={(event) => setLatitude(event.target.value)} required /></label><label>Longitud<input type="number" step="any" value={longitude} onChange={(event) => setLongitude(event.target.value)} required /></label><label className="span-two">Descripción<textarea value={description} onChange={(event) => setDescription(event.target.value)} required minLength={10} placeholder="Qué encontrará el viajero y por qué vale la pena visitarlo." /></label></div>{error && <p className="form-error">{error}</p>}<footer><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? 'Creando…' : 'Guardar como borrador'}</button></footer></form></div>;
}

function ModerationPage({ request }: { request: ReturnType<typeof useApi>['request'] }) {
  const [posts, setPosts] = useState<any[]>([]); const [error, setError] = useState(''); const load = () => request<any>('/admin/posts').then((result) => setPosts(result.data)).catch((reason) => setError(reason.message)); useEffect(() => { void load(); }, []);
  const moderate = async (id: string, status: string) => { await request(`/admin/posts/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); void load(); };
  return <div className="page-content"><section className="page-title-row"><div><h2>Comunidad y moderación</h2><p>Revisa contenido publicado y actúa de forma trazable.</p></div><div className="secure-note"><ShieldCheck size={16} /> Todas las decisiones quedan registradas</div></section>{error && <ErrorState message={error} />}<section className="moderation-list">{posts.map((row) => <article className="panel moderation-card" key={row.post.id}><div className="avatar">{row.fullName.slice(0, 1)}</div><div className="moderation-copy"><div><strong>{row.fullName}</strong><span>@{row.username} · {formatDate(row.post.createdAt)}</span></div><p>{row.post.caption}</p><small><Flag size={13} /> Estado: {row.post.status} · {formatNumber(row.post.likeCount)} reacciones · {formatNumber(row.post.commentCount)} comentarios</small></div><div className="moderation-actions"><button className="button secondary" onClick={() => void moderate(row.post.id, 'review')}>Revisar</button><button className="button danger" onClick={() => void moderate(row.post.id, row.post.status === 'hidden' ? 'published' : 'hidden')}>{row.post.status === 'hidden' ? 'Restaurar' : 'Ocultar'}</button></div></article>)}</section>{!posts.length && <Empty label="No hay publicaciones para moderar." />}</div>;
}

function VerificationsPage({ request }: { request: ReturnType<typeof useApi>['request'] }) {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(''); const load = () => request<any>('/admin/verifications?status=pending').then((result) => setItems(result.data)).catch((reason) => setError(reason.message)); useEffect(() => { void load(); }, []);
  const decide = async (id: string, status: 'approved' | 'rejected') => { await request(`/admin/verifications/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); void load(); };
  return <div className="page-content"><section className="page-title-row"><div><h2>Certificaciones pendientes</h2><p>Valida identidad con criterio humano. Los documentos privados no se exponen en este listado.</p></div><div className="secure-note"><ShieldCheck size={16} /> Tratamiento confidencial</div></section>{error && <ErrorState message={error} />}<section className="verification-grid">{items.map((item) => <article className="panel verification-card" key={item.verification.id}><div className="verification-icon"><FileCheck2 size={23} /></div><div><p className="eyebrow">{item.verification.documentType}</p><h3>{item.fullName}</h3><p>{item.email} · @{item.username}</p><small>Solicitud del {formatDate(item.verification.createdAt)}</small></div><div className="verification-actions"><button className="button secondary" onClick={() => void decide(item.verification.id, 'rejected')}>Rechazar</button><button className="button primary" onClick={() => void decide(item.verification.id, 'approved')}><Check size={16} /> Aprobar</button></div></article>)}</section>{!items.length && <Empty label="No hay certificaciones pendientes. Buen trabajo." />}</div>;
}

function RewardsPage({ request }: { request: ReturnType<typeof useApi>['request'] }) {
  const [badges, setBadges] = useState<any[]>([]); const [recognitions, setRecognitions] = useState<any[]>([]); const [error, setError] = useState(''); useEffect(() => { Promise.all([request<any>('/admin/badges'), request<any>('/admin/recognitions')]).then(([b, r]) => { setBadges(b.data); setRecognitions(r.data); }).catch((reason) => setError(reason.message)); }, []);
  return <div className="page-content"><section className="page-title-row"><div><h2>Sellos, insignias y reconocimientos</h2><p>Los sellos se administran desde cada lugar; aquí controlas los logros transversales.</p></div></section>{error && <ErrorState message={error} />}<section className="dashboard-grid"><article className="panel"><PanelHeader title="Insignias" subtitle={`${badges.length} configuradas`} /><div className="reward-list">{badges.map((item) => <div key={item.id}><div className="reward-art"><Award size={19} /></div><span><strong>{item.name}</strong><small>{item.category} · {item.points} puntos</small></span><i className={item.isActive ? 'active-indicator' : 'inactive-indicator'} /></div>)}</div></article><article className="panel"><PanelHeader title="Reconocimientos" subtitle={`${recognitions.length} configurados`} /><div className="reward-list">{recognitions.map((item) => <div key={item.id}><div className="reward-art gold"><Sparkles size={19} /></div><span><strong>{item.title}</strong><small>{item.category} · {item.partnerName || 'Nómada'}</small></span><i className={item.isActive ? 'active-indicator' : 'inactive-indicator'} /></div>)}</div></article></section></div>;
}

function PanelHeader({ title, subtitle }: { title: string; subtitle: string }) { return <header className="panel-header"><div><h3>{title}</h3><p>{subtitle}</p></div><button className="more-button">•••</button></header>; }
function LoadingState({ label }: { label: string }) { return <div className="loading-state"><LoaderCircle className="spin" size={24} /> {label}</div>; }
function ErrorState({ message }: { message: string }) { return <div className="error-state"><Flag size={19} /><span>{message}</span></div>; }
function Empty({ label }: { label: string }) { return <div className="empty-state"><Sparkles size={24} /><p>{label}</p></div>; }

export default function App() {
  const api = useApi(readSession());
  return api.session ? <AdminShell api={api} /> : <Login onReady={api.setSession} />;
}
