const json = (schema: Record<string, unknown>, example?: Record<string, unknown>) => ({ required: true, content: { 'application/json': { schema, ...(example ? { example } : {}) } } });
const idParameter = { name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } };
const bearer = [{ bearerAuth: [] }];

export const openApiSpec = {
  openapi: '3.0.3',
  info: { title: 'Nómada API', version: 'v1', description: 'API de Nómada · Explora Guatemala. Pulsa **Authorize** y pega el accessToken obtenido al iniciar sesión.' },
  servers: [{ url: 'https://api-nomada.innovasoftgt.com/api', description: 'Producción' }],
  tags: [{ name: 'Health' }, { name: 'Auth' }, { name: 'Account' }, { name: 'Media' }, { name: 'Destinations' }, { name: 'Posts' }, { name: 'Verification' }, { name: 'Passport' }],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Pega solo el accessToken; Swagger añadirá Bearer automáticamente.' } },
    schemas: {
      Register: { type: 'object', required: ['email', 'username', 'password', 'fullName', 'visitorType', 'nationality', 'documentNumber', 'birthDate'], properties: { email: { type: 'string', format: 'email' }, username: { type: 'string', minLength: 3 }, password: { type: 'string', minLength: 8, format: 'password' }, fullName: { type: 'string' }, visitorType: { type: 'string', enum: ['local', 'foreign'] }, nationality: { type: 'string' }, countryCode: { type: 'string', example: 'GT' }, documentType: { type: 'string', enum: ['dpi', 'passport'] }, documentNumber: { type: 'string', example: '1234 56789 0101' }, birthDate: { type: 'string', format: 'date-time', example: '1995-01-01T00:00:00.000Z' }, preferredLanguage: { type: 'string', enum: ['es', 'en'], default: 'es' } } },
      Login: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' } } },
      Session: { type: 'object', properties: { accessToken: { type: 'string' }, refreshToken: { type: 'string' }, expiresIn: { type: 'integer' }, user: { type: 'object' } } },
      ProfileUpdate: { type: 'object', properties: { fullName: { type: 'string' }, city: { type: 'string', nullable: true }, nationality: { type: 'string', nullable: true }, bio: { type: 'string', nullable: true }, avatarKey: { type: 'string', nullable: true }, profileVisibility: { type: 'string', enum: ['public', 'private'] }, preferredLanguage: { type: 'string', enum: ['es', 'en'] } } },
      PostCreate: { type: 'object', required: ['caption', 'mediaKeys'], properties: { caption: { type: 'string', maxLength: 800 }, destinationId: { type: 'string', format: 'uuid' }, visibility: { type: 'string', enum: ['public', 'followers', 'private'], default: 'public' }, mediaKeys: { type: 'array', minItems: 1, items: { type: 'string' } } } },
      Verification: { type: 'object', required: ['documentType', 'documentNumber', 'documentFrontKey', 'selfieKey'], properties: { documentType: { type: 'string', enum: ['dpi', 'passport'] }, documentNumber: { type: 'string' }, documentFrontKey: { type: 'string' }, documentBackKey: { type: 'string' }, selfieKey: { type: 'string' } } },
      Visit: { type: 'object', required: ['destinationId', 'latitude', 'longitude'], properties: { destinationId: { type: 'string', format: 'uuid' }, latitude: { type: 'number' }, longitude: { type: 'number' }, accuracyMeters: { type: 'number' }, evidenceKey: { type: 'string' } } },
    },
  },
  paths: {
    '/v1/health': { get: { tags: ['Health'], summary: 'Estado de API y PostgreSQL', responses: { 200: { description: 'Servicio disponible' } } } },
    '/v1/auth/register': { post: { tags: ['Auth'], summary: 'Crear cuenta', requestBody: json({ $ref: '#/components/schemas/Register' }, { email: 'viajero@example.com', username: 'viajero.gt', password: 'ClaveSegura1', fullName: 'Viajero Nómada', visitorType: 'local', nationality: 'Guatemala', countryCode: 'GT', documentType: 'dpi', documentNumber: '1234 56789 0101', birthDate: '1995-01-01T00:00:00.000Z', preferredLanguage: 'es' }), responses: { 201: { description: 'Cuenta creada', content: { 'application/json': { schema: { $ref: '#/components/schemas/Session' } } } }, 409: { description: 'Correo, usuario o documento ya utilizado' }, 422: { description: 'Datos inválidos' } } } },
    '/v1/auth/login': { post: { tags: ['Auth'], summary: 'Iniciar sesión', requestBody: json({ $ref: '#/components/schemas/Login' }, { email: 'viajero@example.com', password: 'ClaveSegura1' }), responses: { 200: { description: 'Sesión creada', content: { 'application/json': { schema: { $ref: '#/components/schemas/Session' } } } }, 401: { description: 'Credenciales inválidas' } } } },
    '/v1/auth/refresh': { post: { tags: ['Auth'], summary: 'Renovar sesión', requestBody: json({ type: 'object', required: ['refreshToken'], properties: { refreshToken: { type: 'string' } } }), responses: { 200: { description: 'Token renovado' } } } },
    '/v1/auth/forgot-password': { post: { tags: ['Auth'], summary: 'Solicitar recuperación', requestBody: json({ type: 'object', required: ['email'], properties: { email: { type: 'string', format: 'email' } } }, { email: 'viajero@example.com' }), responses: { 200: { description: 'Solicitud recibida' } } } },
    '/v1/auth/reset-password': { post: { tags: ['Auth'], summary: 'Restablecer contraseña', requestBody: json({ type: 'object', required: ['token', 'password'], properties: { token: { type: 'string' }, password: { type: 'string', minLength: 8, format: 'password' } } }), responses: { 200: { description: 'Contraseña actualizada' } } } },
    '/v1/auth/logout': { post: { tags: ['Auth'], summary: 'Cerrar sesión', security: bearer, responses: { 204: { description: 'Sesión cerrada' } } } },
    '/v1/me': { get: { tags: ['Account'], summary: 'Mi cuenta', security: bearer, responses: { 200: { description: 'Cuenta actual' } } } },
    '/v1/me/profile': { patch: { tags: ['Account'], summary: 'Actualizar perfil', security: bearer, requestBody: json({ $ref: '#/components/schemas/ProfileUpdate' }, { fullName: 'Viajero Nómada', city: 'Guatemala', bio: 'Explorando nuevos caminos.' }), responses: { 200: { description: 'Perfil actualizado' } } } },
    '/v1/me/change-password': { post: { tags: ['Account'], summary: 'Cambiar contraseña', security: bearer, requestBody: json({ type: 'object', required: ['currentPassword', 'newPassword'], properties: { currentPassword: { type: 'string', format: 'password' }, newPassword: { type: 'string', minLength: 8, format: 'password' } } }), responses: { 200: { description: 'Contraseña actualizada' } } } },
    '/v1/media': { post: { tags: ['Media'], summary: 'Subir imagen', security: bearer, parameters: [{ name: 'kind', in: 'query', required: true, schema: { type: 'string', enum: ['profile', 'post', 'visit', 'identity'] } }, { name: 'slot', in: 'query', schema: { type: 'string' } }], requestBody: { required: true, content: { 'image/jpeg': { schema: { type: 'string', format: 'binary' } }, 'image/png': { schema: { type: 'string', format: 'binary' } }, 'image/webp': { schema: { type: 'string', format: 'binary' } } } }, responses: { 201: { description: 'Archivo guardado' } } } },
    '/v1/destinations': { get: { tags: ['Destinations'], summary: 'Listar destinos', responses: { 200: { description: 'Destinos activos' } } } },
    '/v1/destinations/{id}': { get: { tags: ['Destinations'], summary: 'Detalle de destino', parameters: [idParameter], responses: { 200: { description: 'Destino' } } } },
    '/v1/posts': { get: { tags: ['Posts'], summary: 'Feed público', responses: { 200: { description: 'Publicaciones' } } }, post: { tags: ['Posts'], summary: 'Crear publicación', security: bearer, requestBody: json({ $ref: '#/components/schemas/PostCreate' }), responses: { 201: { description: 'Publicación creada' } } } },
    '/v1/posts/{id}/like': { post: { tags: ['Posts'], summary: 'Dar me gusta', security: bearer, parameters: [idParameter], responses: { 200: { description: 'Like registrado' } } }, delete: { tags: ['Posts'], summary: 'Quitar me gusta', security: bearer, parameters: [idParameter], responses: { 204: { description: 'Like eliminado' } } } },
    '/v1/posts/{id}/comments': { post: { tags: ['Posts'], summary: 'Comentar publicación', security: bearer, parameters: [idParameter], requestBody: json({ type: 'object', required: ['body'], properties: { body: { type: 'string', maxLength: 500 } } }, { body: 'Excelente aventura.' }), responses: { 201: { description: 'Comentario creado' } } } },
    '/v1/verification': { post: { tags: ['Verification'], summary: 'Enviar certificación', security: bearer, requestBody: json({ $ref: '#/components/schemas/Verification' }), responses: { 201: { description: 'Certificación en revisión' } } } },
    '/v1/verification/status': { get: { tags: ['Verification'], summary: 'Estado de certificación', security: bearer, responses: { 200: { description: 'Estado actual' } } } },
    '/v1/visits/validate': { post: { tags: ['Passport'], summary: 'Validar visita y generar sello', security: bearer, requestBody: json({ $ref: '#/components/schemas/Visit' }), responses: { 201: { description: 'Visita validada' }, 422: { description: 'Fuera del radio permitido' } } } },
    '/v1/passport': { get: { tags: ['Passport'], summary: 'Mi pasaporte digital', security: bearer, responses: { 200: { description: 'Puntos y sellos del viajero' } } } },
  },
} as const;
