export const openApiSpec = {
  openapi: '3.0.3',
  info: {
    title: 'Nómada API',
    version: 'v1',
    description: 'API de Nómada · Explora Guatemala para autenticación, publicaciones, visitas, certificados y medios.',
  },
  servers: [{ url: 'https://api-nomada.innovasoftgt.com/api', description: 'Producción' }],
  tags: [
    { name: 'Health' },
    { name: 'Auth' },
    { name: 'Account' },
    { name: 'Media' },
    { name: 'Destinations' },
    { name: 'Posts' },
    { name: 'Verification' },
    { name: 'Passport' },
  ],
  paths: {
    '/v1/health': { get: { tags: ['Health'], summary: 'Health check' } },
    '/v1/supabase/me': { get: { tags: ['Auth'], summary: 'Validate Supabase JWT' } },
    '/v1/auth/register': { post: { tags: ['Auth'], summary: 'Register account' } },
    '/v1/auth/login': { post: { tags: ['Auth'], summary: 'Login' } },
    '/v1/auth/refresh': { post: { tags: ['Auth'], summary: 'Refresh session' } },
    '/v1/auth/logout': { post: { tags: ['Auth'], summary: 'Logout' } },
    '/v1/auth/forgot-password': { post: { tags: ['Auth'], summary: 'Request password reset' } },
    '/v1/auth/reset-password': { post: { tags: ['Auth'], summary: 'Reset password' } },
    '/v1/me': { get: { tags: ['Account'], summary: 'Current account' } },
    '/v1/me/profile': { patch: { tags: ['Account'], summary: 'Update profile' } },
    '/v1/me/change-password': { post: { tags: ['Account'], summary: 'Change password' } },
    '/v1/media': { post: { tags: ['Media'], summary: 'Upload media' } },
    '/v1/media/fotos/{key}': { get: { tags: ['Media'], summary: 'Read public or owner-protected media' } },
    '/v1/media/documentos/{key}': { get: { tags: ['Media'], summary: 'Read owner-private documents' } },
    '/v1/destinations': { get: { tags: ['Destinations'], summary: 'List destinations' } },
    '/v1/destinations/{id}': { get: { tags: ['Destinations'], summary: 'Get destination' } },
    '/v1/posts': { get: { tags: ['Posts'], summary: 'List posts' }, post: { tags: ['Posts'], summary: 'Create post' } },
    '/v1/posts/{id}/like': { post: { tags: ['Posts'], summary: 'Like post' }, delete: { tags: ['Posts'], summary: 'Unlike post' } },
    '/v1/posts/{id}/comments': { post: { tags: ['Posts'], summary: 'Comment on post' } },
    '/v1/verification': { post: { tags: ['Verification'], summary: 'Submit identity verification' } },
    '/v1/verification/status': { get: { tags: ['Verification'], summary: 'Verification status' } },
    '/v1/visits/validate': { post: { tags: ['Passport'], summary: 'Validate visit and award stamp' } },
    '/v1/passport': { get: { tags: ['Passport'], summary: 'Get digital passport' } },
  },
} as const;
